apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter
    name: node-exporter
  name: node-exporter-cip
  namespace: default
spec:
  ports:
  - name: scrape
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: node-exporter
  type: ClusterIP
  clusterIP: 10.96.170.208
